language: node_js
node_js:
  - lts/*
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.32.4/hugo_0.32.4_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
cache:
  directories:
    - node_modules
script:
  - npm run test
deploy:
  skip_cleanup: true
  provider: firebase
  on:
    tags: true
  token:
    secure: zltO50j5i8Bz4X27usjxQ2JsahuL4l4XpC0PMV/3TJUYIvlSVK+piJA0GRCBNAJjuoRQkTETrCRZMHVl0l18Wfy8SSSDyjMGbg8UklFCUDGGGw6kgDeLAFRHHNFvWiZSRl+a+pByn5i2c/bpYYQPNs1kbqL8F9Y7u39K+hI3I3YNubJ7FfNMag1Y4II2fUTYLvC7t6kSEFd4CWUKaQh4Ha5qqa4jfclxoezx4wos+nzzJlsiOkh7+hDLWp5/9eD4a4Uo85Se9mMty6zwWmTzCQV9misAVJ0/fjNmt0WlCAD4Nx/qLhGJnYXXK05kAGI659DVjXY0oQFzwvByYwZEF8hyfK0zlP0S1Afjobh4zIEaOr+4msLvSkhkgGgcg8svXcGZN1KFCG8T0wFX8UWH0D+jJSztSwtFkZrEgyqHPBLuwi4s9sVf731X00fh4x7fR01fTTver9osYzxkjr0WcMVNxuq0EJjazpKCucHMefBtpeK/+w3sys99SSZQXeCD1ipbBRJRT6wq9YhvpYpKd3B+heRrO7DsxwjLrEqjz4yWr5ffic1Kp+2Cjs9tXw+E9NmhgfCFh1KrwMXsACOVm7RDJma1m5RT1s1qLtLfgrCuOM1dY+2VvUEu8g+1fqrqQZT1M8Tz2LhF1IYdBmLin+BRjbT4Vc0Ll4rptr4lb2o=
