name: Deploy

on:
  push:
    tags:
      - v2.*

jobs:
  deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install Firebase CLI
      run: |
        npm install -g firebase-tools
        firebase --version
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: hugo --minify
    - name: GitHub Pages Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
