name: Deploy

on:
  push:
    tags:
      - v2.*
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: latest
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: hugo --minify
    - name: GitHub Pages Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
